version: "3.9"


services:
  #Nombre del servicio
  app:
    # Construir el contexto en el directorio donde se encuentra el archivo
    build:
      context: .
      # Sobreescribe el valor del argumento DEV para indicar que estamos en modo de desarrollo
      args:
        - DEV=true
    # Mapeo de puertos local:maquina-virtual
    ports:
      - "8000:8000"
    # Mapeo de directorios local:container, queremos que las modificaciones se vean reflejadas 
    # en el container en tiempo real y no reconstruir la imagen con cada cambio
    volumes:
      - ./app:/app
    # Comando que se usara para arrancar el servicio
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: